#!/bin/sh
set -e

if [ -f .env ]; then
    echo '\n[info]: .env file detected'
fi

if [ !  -z $DOPPLER_TOKEN ]; then
    echo '\n[info]: Generating .env file using Doppler CLI\n'
    HOME=/usr/src/app doppler secrets download --no-file --format env-no-quotes > .env
else
    echo '\n[info]: $DOPPLER_TOKEN not found so skipping creation of .env file\n'
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
