#!/bin/sh
set -e

if [ !  -z $DOPPLER_TOKEN ]; then
    echo '\n[info]: Generating env vars using Doppler CLI\n'
    doppler secrets download --no-file | jq -r '. | to_entries[] | "env[\(.key)] = \(.value)"' > /usr/local/etc/php-fpm.d/env-vars.conf
else
    echo '\n[info]: $DOPPLER_TOKEN not found so skipping creation of env vars file\n'
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
